version: "2"
services:

  o4act:
    image: "pics"
    build:
      context: build-pics
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db-pics
  db-o4act:
    image: "postgres:13-alpine"
    volumes:
      - ./pgdata-pics:/var/lib/postgresql/data
      # create avolume in order not to lose data when the docker machine is off .
      # /var/lib/postgresql/data where postgresql server saves the data 
      # cat build-pics/pics/databases/data_vierge.dump | grep -v DROP | grep -v grep > build-pics/docker-entrypoint-initdb.d/init.sql
      - ./build-pics/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=orka
      - POSTGRES_PASSWORD=orika
      - POSTGRES_DB=pics
